---
name: GitHub-Pages

on:
    push:
        branches:
            - master
        paths:
            - docs/**
    pull_request:
    workflow_call:
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
        inputs:
            destination-dir:
                description: "Path where to store documentation on gh-pages branch"
                required: true
                type: string
            checkout-code:
                description: "Do we git checkout code and install first"
                required: false
                default: true
                type: boolean

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    deploy:
        name: Deploy to GH Pages

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                php:
                    - 7.4

        steps:
            -   # Git Checkout
                if: ${{ inputs.checkout-code }}
                name: Checkout Code
                uses: actions/checkout@v2
                with:
                    persist-credentials: false

            -   # Setup PHP runtime
                if: ${{ inputs.checkout-code }}
                name: Setup PHP runtime
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   # Install Composer dependencies
                if: ${{ inputs.checkout-code }}
                name: Install Composer dependencies
                uses: ramsey/composer-install@v2
                with:
                    dependency-versions: "highest"
                    composer-options: "--prefer-dist --no-scripts"

            -   # Setup Python version
                name: Set up Python runtime
                uses: actions/setup-python@v2
                with:
                    python-version: 3.x

            -   # Install Material for MkDocs
                name: Install Material for MkDocs
                run: pip install mkdocs-material

            -   # Build Documentation
                name: Build Docs
                run: mkdocs build

            -   # Deploy Documentation
                name: Deploy Docs
                uses: peaceiris/actions-gh-pages@v3
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./site
                    destination_dir: ${{ inputs.destination-dir }}
                    full_commit_message: "Deployed ${{ github.sha }} with MkDocs"
                    force_orphan: true
                    user_name: 'github-actions'
                    user_email: 'github-actions@users.noreply.github.com'
