---
name: GitHub-Pages

on:
    push:
        branches:
            - master
        paths:
            - docs/**
    pull_request:
    workflow_call:
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
        inputs:
            php-version:
                description: "PHP runtime version in format Major.minor"
                required: false
                default: "8.1"
                type: string
            php-extensions:
                description: "PHP runtime extensions you want to add or disable"
                default: ""
                required: false
                type: string
            destination-dir:
                description: "Path where to store documentation on gh-pages branch"
                required: true
                type: string
            force-orphan:
                description: "Allows you to make your publish branch with only the latest commit"
                required: false
                default: true
                type: boolean
            hook-script:
                description: "Hook script to run custom project task before deploying documentation"
                required: false
                type: string
            graph-uml:
                description: "Draw UML graphs"
                required: false
                default: false
                type: boolean
            graph-composer:
                description: "Draw Composer graphs"
                required: false
                default: false
                type: boolean
            composer-options:
                description: "Composer options for ramsey/composer-install GitHub Action"
                default: "--prefer-dist --no-scripts"
                required: false
                type: string

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    deploy:
        name: Deploy to GH Pages

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-22.04
                php:
                    - ${{ inputs.php-version }}
                extensions:
                    - ${{ input.php-extensions }}

        steps:
            -   # https://github.com/actions/checkout
                name: Checkout Code
                uses: actions/checkout@v4
                with:
                    persist-credentials: false
                    fetch-depth: 0

            -   # Setup Libraries
                name: Setup Libraries
                run: |
                    sudo apt-get update
                    sudo apt-fast install graphviz -y

            -   # https://github.com/shivammathur/setup-php
                name: Setup PHP runtime
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: ${{ matrix.extensions }}

            -   # https://github.com/ramsey/composer-install
                name: Install Composer dependencies
                uses: ramsey/composer-install@v3
                with:
                    dependency-versions: "highest"
                    composer-options: ${{ inputs.composer-options }}

            -   # https://github.com/llaville/umlwriter
                name: Download UmlWriter Artifact
                if: ${{ inputs.graph-uml }}
                run: |
                    curl -Ls https://github.com/llaville/umlwriter/releases/download/4.1.0/umlwriter.phar -o "${GITHUB_WORKSPACE}/resources/umlwriter.phar"

            -   # https://github.com/llaville/graph-composer.git
                name: Download Graph-Composer Artifact
                if: ${{ inputs.graph-composer }}
                run: |
                    curl -Ls https://github.com/llaville/.github/releases/download/0.1.0/graph-composer.phar -o "${GITHUB_WORKSPACE}/resources/graph-composer.phar"

            -   # Hook to run custom project task before deploying documentation
                name: Hook to run custom project task
                if: endsWith(inputs.hook-script, '.sh')
                shell: bash
                run: |
                    "${GITHUB_WORKSPACE}/${{ inputs.hook-script }}"

            -   # https://github.com/actions/setup-python
                name: Set up Python runtime
                uses: actions/setup-python@v5
                with:
                    python-version: 3.x

            -   # https://github.com/squidfunk/mkdocs-material
                name: Install Material for MkDocs
                run: pip install mkdocs-material

            -   # https://github.com/oprypin/markdown-callouts
                name: Install Markdown Callouts
                run: pip install markdown-callouts

            -   # https://github.com/pa-decarvalho/mkdocs-asciinema-player
                # https://github.com/asciinema/asciinema-player
                name: Install Mkdocs asciinema player
                run: pip install mkdocs-asciinema-player

            -   # https://github.com/squidfunk/mkdocs-material
                name: Build Docs
                run: mkdocs build

            -   # https://github.com/peaceiris/actions-gh-pages
                name: Deploy Docs
                uses: peaceiris/actions-gh-pages@v4
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./site
                    destination_dir: ${{ inputs.destination-dir }}
                    full_commit_message: "Deployed ${{ github.sha }} with MkDocs"
                    force_orphan: ${{ inputs.force-orphan }}
                    user_name: 'github-actions'
                    user_email: 'github-actions@users.noreply.github.com'
