---
name: Release

on:
    push:
        branches:
            - "[0-9]+.[0-9]+"
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"
    workflow_call:
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
        inputs:
            box-output:
                description: "Path to the PHP Archive made by the BOX"
                required: true
                type: string
            box-manifest-bootstrap:
                description: "A PHP script that is included before compile run (custom autoloader)"
                required: false
                type: string
            repository:
                description: "Name of working repository"
                required: false
                type: string
            php-version:
                description: "PHP runtime version in format Major.minor"
                required: false
                default: "7.4"
                type: string
            release-prerelease:
                description: "Indicator of whether or not is a prerelease"
                required: false
                default: false
                type: boolean
            release-draft:
                description: "Indicator of whether or not this release is a draft"
                required: false
                default: false
                type: boolean
            legacy:
                description: "Legacy version that use a 'resources/release/build.php' script"
                required: false
                default: true
                type: boolean
            changie-command-args:
                description: "Changie tool command arguments"
                required: false
                default: "batch --keep --prerelease snapshot minor"
                type: string

jobs:
    build:
        # do not run on TEMPLATE repository
        if: github.repository == inputs.repository
        runs-on: ${{ matrix.os }}

        env:
            CHANGIE_VERSION: v1.10.1

        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                php:
                    - ${{ inputs.php-version }}

        steps:
            -   # Git Checkout
                name: Checkout
                uses: actions/checkout@v3

            -   # Setup PHP runtime
                name: Setup PHP runtime
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   # Install Composer dependencies
                name: Install Composer dependencies
                uses: ramsey/composer-install@v2
                with:
                    composer-options: "--prefer-dist"

            -   # Build the current release changelog
                name: Build Release Notes (by legacy script)
                if: inputs.legacy == true
                run: |
                    resources/release/build.php

            -   # Build the current change fragments for pre-release version (snapshot)
                name: Build Release Notes (by Changie tool)
                if: inputs.legacy == false && inputs.release-prerelease == true
                uses: miniscruff/changie-action@v0
                with:
                    version: ${{ env.CHANGIE_VERSION }}
                    args: ${{ inputs.changie-command-args }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   # Build the current release changelog
                name: Build Release Notes (by Changie tool)
                if: inputs.legacy == false
                uses: miniscruff/changie-action@v0
                with:
                    version: ${{ env.CHANGIE_VERSION }}
                    args: merge
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   # Build the current release with artifacts (php archive)
                name: Build Release Artifacts (without bootstrap file)
                if: endsWith(inputs.box-output, '.phar')
                uses: docker://ghcr.io/llaville/box-manifest:latest
                with:
                    entrypoint: /usr/local/src/box-manifest/bin/box
                    args: compile

            -   # Build the current release with artifacts (php archive with a custom autoloader)
                name: Build Release Artifacts (with bootstrap file)
                if: endsWith(inputs.box-output, '.phar') && endsWith(inputs.box-manifest-bootstrap, '.php')
                uses: docker://ghcr.io/llaville/box-manifest:latest
                with:
                    entrypoint: /usr/local/src/box-manifest/bin/box
                    args: compile --bootstrap $ {{ inputs.box-manifest-bootstrap }}

            -   # Create a new Release (from a tag)
                name: Create Release with legacy notes
                uses: softprops/action-gh-release@v1
                if: github.ref_type == 'tag' && inputs.legacy == true
                with:  # https://github.com/softprops/action-gh-release#-customizing
                    prerelease: ${{ inputs.release-prerelease }}
                    draft: ${{ inputs.release-draft }}
                    body_path: ${{ github.workspace }}/releaseNotes.md
                    # https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets
                    files:
                        ${{ inputs.box-output }}
                    fail_on_unmatched_files: true

            -   # Create a new Release (from a branch)
                name: Create Release from current branch
                uses: softprops/action-gh-release@v1
                if: github.ref_type == 'branch' && inputs.legacy == false && inputs.release-prerelease == true
                with:  # https://github.com/softprops/action-gh-release#-customizing
                    prerelease: ${{ inputs.release-prerelease }}
                    draft: ${{ inputs.release-draft }}
                    body_path: ${{ github.workspace }}/.changes/${{github.ref_name}}.0-snapshot.md
                    # https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets
                    files:
                        ${{ inputs.box-output }}
                    fail_on_unmatched_files: true

            -   # Create a new Release (from a tag)
                name: Create Release from current tag
                uses: softprops/action-gh-release@v1
                if: github.ref_type == 'tag' && inputs.legacy == false
                with:  # https://github.com/softprops/action-gh-release#-customizing
                    prerelease: ${{ inputs.release-prerelease }}
                    draft: ${{ inputs.release-draft }}
                    body_path: ${{ github.workspace }}/.changes/${{github.ref_name}}.md
                    # https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets
                    files:
                        ${{ inputs.box-output }}
                    fail_on_unmatched_files: true
