---
name: Release

on:
    push:
        branches:
            - "[0-9]+.[0-9]+"
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"
    workflow_call:
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
        inputs:
            box-output:
                description: "Path to the PHP Archive made by the BOX"
                required: true
                type: string
            box-manifest-bootstrap:
                description: "A PHP script that is included before compile run (custom autoloader)"
                required: false
                type: string
            repository:
                description: "Name of working repository"
                required: false
                type: string
            php-version:
                description: "PHP runtime version in format Major.minor"
                required: false
                default: "8.1"
                type: string
            release-prerelease:
                description: "Indicator of whether or not is a prerelease"
                required: false
                default: false
                type: boolean
            release-draft:
                description: "Indicator of whether or not this release is a draft"
                required: false
                default: false
                type: boolean
            legacy:
                description: "Legacy version that use a 'resources/release/build.php' script"
                required: false
                default: false
                type: boolean

jobs:
    build:
        # do not run on TEMPLATE repository
        if: github.repository == inputs.repository
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-22.04
                php:
                    - ${{ inputs.php-version }}

        steps:
            -   # https://github.com/actions/checkout
                name: Checkout
                uses: actions/checkout@v4

            -   # https://github.com/shivammathur/setup-php
                name: Setup PHP runtime
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   # https://github.com/ramsey/composer-install
                name: Install Composer dependencies
                uses: ramsey/composer-install@v2
                with:
                    composer-options: "--prefer-dist"

            -   # https://github.com/llaville/box-manifest
                name: Build Release Artifacts (without bootstrap file)
                if: endsWith(inputs.box-output, '.phar')
                uses: docker://ghcr.io/llaville/box-manifest:latest
                with:
                    entrypoint: /usr/local/src/box-manifest/bin/box
                    args: compile

            -   # https://github.com/llaville/box-manifest
                name: Build Release Artifacts (with bootstrap file)
                if: endsWith(inputs.box-output, '.phar') && endsWith(inputs.box-manifest-bootstrap, '.php')
                uses: docker://ghcr.io/llaville/box-manifest:latest
                with:
                    entrypoint: /usr/local/src/box-manifest/bin/box
                    args: compile --bootstrap $ {{ inputs.box-manifest-bootstrap }}

            -   # https://github.com/softprops/action-gh-release
                name: Create Release from current branch
                uses: softprops/action-gh-release@v1
                if: github.ref_type == 'branch' && inputs.legacy == false && inputs.release-prerelease == true
                with:  # https://github.com/softprops/action-gh-release#-customizing
                    prerelease: ${{ inputs.release-prerelease }}
                    draft: ${{ inputs.release-draft }}
                    body_path: ${{ github.workspace }}/.changes/${{ steps.upcoming.outputs.output }}.md
                    # https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets
                    files:
                        ${{ inputs.box-output }}
                    fail_on_unmatched_files: true

            -   # https://github.com/softprops/action-gh-release
                name: Create Release from current tag
                uses: softprops/action-gh-release@v1
                if: github.ref_type == 'tag' && inputs.legacy == false
                with:  # https://github.com/softprops/action-gh-release#-customizing
                    prerelease: ${{ inputs.release-prerelease }}
                    draft: ${{ inputs.release-draft }}
                    body_path: ${{ github.workspace }}/.changes/${{github.ref_name}}.md
                    # https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets
                    files:
                        ${{ inputs.box-output }}
                    fail_on_unmatched_files: true
